### ISSUE TITLE
What Happened to the Fallout Mod?

### ISSUE THREAD

**Issue by TurtleShroom** [vawser/Fallout-Mod#1]
Good afternoon!

It's been a honor contributing to the "Fallout" Mod, and I am very excited to continue working on it.

I seem to be experiencing an issue, however. On the Steam Console AND the Github console, it claims that the "Fallout" Mod and the old incarnation where all of the Idea Suggestions has been completely deleted. Furthermore, the Discord chat room is gone as well!

This is in spite of it clearly stating that the Fallout Mod still exists on the Github (here). 

What happened? Was there an error? Are the Mod's core aspects being completely rewritten per Xylozi's dreams of an epic new map?

I have no problem with any of these things, of course, I'm just curious as to why the best EU4 Mod ever made  is gone.

Thank you for any assistance you may render.
-TURTLESHROOM

P.S.: Have I done something wrong? If it involves the Interface edit that literally broke the Mod UI... I can always fix that bag with a few clicks. It's not irreversible and I actually have the original files from that particular Commitment.

**Comment by vawser** [comment]
Sorry, I snapped. All the user comments about the Warcraft mod and then you reverting my commit really annoyed me. 

I didn't grant people permission to push to the repository just for my own work to be removed. I know it is easily reverted, but it was really the confluence of this and many other comments in the past that got to me.

Regarding the interface, if the issue was you didn't like the design, then you should have just said so on the discord rather than reverting the commit. If the interface was actually broken, then that is an issue on your end since it is perfectly functional on my end.

I will re-make the Discord and restore the collaborators here.

**Comment by TurtleShroom** [comment]
Were those past comments mine?

My reversion of the abominable UI was out of a sincere belief that it broke the Mod. I couldn't access any of the detail screens except by a single notification that doesn't always appear. Everything was gone.

While I despise your UI change with the white-hot intensity of one thousand suns, I would NEVER, EVER revert it solely because I hated it!

I would have told you how bad it is and explain my reasoning.

**Comment by vawser** [comment]
The comments is more referring to people constantly demanding more stuff and then complaining about about tiny details. Not you specifically.

Sounds like the mod files were corrupted in some way for that to happen to the interface.

**Comment by TurtleShroom** [comment]
Okay. Can you put the Discord chat room back up now? Insert and I can't get into the Discord chat room. We are both told the invitation is invalid.

-and what happened to the "Fallout - OLD" Mod that was depracated? I need access to that because ALL of the suggestions and such were stored on it. I was going to implement proper Ideas for things using the suggestions provided.

**Comment by vawser** [comment]
https://discord.gg/HMtacPz
